### ISSUE TITLE
How to detect the underlying stream authentication issues with async subscriber

### ISSUE THREAD

**Issue by j256** [googleapis/java-pubsub#1824]
We are using the `com.google.cloud.pubsub.v1.Subscriber` and the `MessageReceiver` to subscribe to pubsub topics.  Under the covers we are seeing GRPC errors when the authentication token expires which causes "stream closed with retryable exception" log messages but no mechanism that I can see to detect that the underlying subscriber is in effect disconnected.

What are we supposed to do to figure this out?

* Is there a callback that we can add to validate the underlying network connections are having problems?
* Would a call to the `SubscriptionAdminClient.getSubscription(...)` be enough to detect the authentication issues?
* Is there a call that I can make to the `CredentialsProvider` or underlying `Credentials` to see if they are still valid?

Thanks for any assistance.

**Comment by maitrimangal** [comment]
Hi, thanks for the question. If the subscriber has been disconnected for a long time then you should get an "unrecoverable error".

In terms of how to set the credentials you can do so by using `setCredentialsProvider()`.

I don't believe getSubscription will really give you the details of authentication because [it returns](https://cloud.google.com/java/docs/reference/google-cloud-pubsub-bom/latest/com.google.cloud.pubsub.v1.SubscriptionAdminClient#com_google_cloud_pubsub_v1_SubscriptionAdminClient_getSubscription_com_google_pubsub_v1_GetSubscriptionRequest_) the type Subscription which is [this](https://cloud.google.com/java/docs/reference/google-cloud-pubsub-bom/latest/com.google.pubsub.v1.Subscription)

If you need more logging you can turn up log level in you log properties file to DEBUG - not sure if youve already done that?

Additionally, for callback functions you can perhaps try using some of the [AbstractApiService Methods](https://googleapis.github.io/api-common-java/0.2.0/apidocs/com/google/api/core/AbstractApiService.html) such as notifyFailed(), or isRunning()?

If you need us to debug further into why the authentication is failing - you should open a customer issue case with Google! Thank you

**Comment by j256** [comment]
Thanks for the response.  We see the subscriber run for hours with retryable failures.  The authentication tokens are appropriately timing out so we know _why_ it is happening.  We are just trying to detect it from the subscriber standpoint.

If the authentication tokens have expired I assume that a `getSubscription()` call will fail?  I don't think that the state of the service has been affected but I will check if `notifyFailed()` or `isRunning()` has been effected.

**Comment by j256** [comment]
Yeah calling the `SubscriptionAdminClient.getSubscription(...)` using the same `CredentailsProvider` in the background was a good mechanism to see if the authentication had failed.  Again, the `Subscriber` object wasn't able to detect any issues but the `getSubscription(...)` request was.  This solved our issue on how to detect this condition and gracefully shutdown the subscriber in these situations.
