### ISSUE TITLE
Is this library suitable for receiving a message from the server on a client?

### ISSUE THREAD

**Issue by ScottPierce** [googleapis/java-pubsub#436]
I have a java client application, and an Android client application. Would this library be suitable to use on the clients (Java and Android) to receive messages from the server (Firebase Functions)? I ask because several `googleapis` libraries seem to only be designed with the server in mind.

**Comment by anguillanneuf** [comment]
@ScottPierce It sounds like you want Pub/Sub publishers in your Firebase Functions, and Pub/Sub subscribers in your Java and Android applications. I don't see why not. Can you share which other `googleapis` do not support such set up?

Your Android application will need to be authorized so that the Pub/Sub subscriber can establish a connection with the Pub/Sub servers and receive messages. This is usually done via a service account and a service account key. 

Alternatively, you can use a push subscription instead of using a subscriber in your application code. With a push subscription, you can check the JWT in the push message header to decide whether or not to let the message in your application.
