### ISSUE TITLE
Can you consume a pubsub subscription and detect when it is empty and exit?

### ISSUE THREAD

**Issue by jkleckner** [googleapis/java-pubsub#448]
The samples such as [1] use a fixed amount of time to wait and then issue a stop async for the subscriber.

Is there a supported way to detect when the queue has been drained and exit?

Obviously it would be possible to keep a variable for time last updated and monitor that to detect that no events have been processed, but I was hoping for an in-built mechanism.

[1] https://github.com/googleapis/java-pubsub/blob/master/samples/snippets/src/main/java/pubsub/SubscribeWithErrorListenerExample.java

**Comment by anguillanneuf** [comment]
@jkleckner I want to know why it's important to you to shut down the subscriber when using pull subscriptions. I feel that if the goal is to *wake up your application when there are messages, a push subscription would work better.* 

A pull subscription is meant to keep a streaming connection open. You can choose to shut down a subscriber any time you want, because Pub/Sub will hold on to any messages not yet delivered.

Does this make sense?
