### ISSUE TITLE
PullRequest: unable to set filter

### ISSUE THREAD

**Issue by amarkevich** [googleapis/java-pubsub#868]
**Is your feature request related to a problem? Please describe.**

gcloud [1] allows to specify filter for pull like
`gcloud pubsub subscriptions pull $SUBS --filter=message.attributes.deviceId=$DEV_ID`

PullRequest have no such configuration

1. https://cloud.google.com/sdk/gcloud/reference/pubsub/subscriptions/pull

**Describe the solution you'd like**
```
PullRequest.newBuilder()
    .setFilter("message.attributes.deviceId=" + DEV_ID)
```

**Describe alternatives you've considered**
No any workaround in current implementation

**Comment by maitrimangal** [comment]
We have moved this issue to our internal tracking system. However, the issue is considered low-priority at this time. If the issue is ultimately resolved, it will appear in the release notes for the client at that time. If this issue is of higher priority for you, please enter a support ticket for follow-up. Thanks

internal bug: b/278076145
